// eslint-disable-next-line @typescript-eslint/no-var-requires
require('dotenv').config();

//API URL

const API_URL = process.env.API_URL;
//HTTP CONSTANTS
const INTERNAL_SERVER_ERROR = 'INTERNAL SERVER ERROR';
const UNPROCESIBLE_ENTITY_ERROR = 'UNPROCESSABLE ENTITY EXCEPTION';

//PAGINATION CONSTANTS
const DEFAULT_PAGE_LIMIT = 10;
const DEFAULT_PAGE_NUMBER = 1;

//API VERSIONING CONSTANTS
const GLOBAL_PREFIX = 'api';
const API_VERSION_1 = '1';

//REQUEST PROXY CONSTANTS
const REQUEST_PROXY_TIMEOUT = 5000;
const REQUEST_PROXY_MAX_REDIRECTS = 5;

export {
  INTERNAL_SERVER_ERROR,
  UNPROCESIBLE_ENTITY_ERROR,
  DEFAULT_PAGE_LIMIT,
  DEFAULT_PAGE_NUMBER,
  GLOBAL_PREFIX,
  API_VERSION_1,
  REQUEST_PROXY_TIMEOUT,
  REQUEST_PROXY_MAX_REDIRECTS,
  API_URL,
};
